name: Gradle java application test
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      vendor:
        type: string
        default: corretto
      jdkVersion:
        type: string
        default: '17'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.jdkVersion }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.vendor }}
        java-version: ${{ inputs.jdkVersion }}
    - name: Run gradle tests
      run: |
        echo "Environment: ${{ inputs.environment }}"
        echo "Project: ${{ inputs.project }}"
        echo "Vendor: ${{ inputs.vendor }}"
        echo "JDK Version: ${{ inputs.jdkVersion }}"
        ./gradlew test
