name: Java application Test
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      vendor:
        required: true
        type: string
        default: corretto
      jdkVersion:
        required: true
        type: string
        default: '17'
      image:
        required: true
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.jdkVersion }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.vendor }}
        java-version: ${{ inputs.jdkVersion }}
    - name: Run gradle tests
      run: ./gradlew test
